name: Build, Test & Lint
on: [push, pull_request]
jobs:
  test:
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['2.7', '3.0', '3.1', head]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake
    - name: Upload Coverage Report Artifact # So it's accessible in other jobs
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage
  coverage:
    needs: [ test ]
    name: Publish Code Coverage
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    runs-on: ubuntu-latest
    steps:
    - name: Download Coverage Report Artifact from "Test" Job
      uses: actions/download-artifact@v3
      with:
        name: coverage
    - name: Upload Code Coverage Report to Code Climate
      uses: paambaati/codeclimate-action@v3.0.0
      with:
        debug: true
        coverageLocations: "${{github.workspace}}/coverage/coverage.json:simplecov"
